# Generated by Django 6.1 on 2026-08-26 11:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('cow', 'Cow'), ('goat', 'Goat'), ('sheep', 'Sheep'), ('poultry', 'Poultry'), ('pig', 'Pig')], max_length=30)),
                ('breed', models.CharField(max_length=200)),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('age_months', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('breeding', 'Breeding'), ('sold', 'Sold')], default='healthy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livestock_created', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock', to='farms.farm')),
            ],
            options={
                'ordering': ['breed'],
            },
        ),
    ]
